### ISSUE TITLE
There is no documentation

### ISSUE THREAD

**Issue by markomitranic** [miningape/are-you-in#1]
Dear @miningape thank you for making this amazing project. I suspect, however, that global adoption of it is purely hindered by the fact that not enough people know about your effort! Adding some documentation in the Readme would help immensely!

Is this a website? Is it a chrome extension? What does it do? Are you applying for a job somewhere? Who knows...

**Comment by miningape** [comment]
@markomitranic I can't handle you 😂 I'll see what I can do. 

To satisfy that burning curiosity of yours: its an app to track who is in/out of the office for the day lol

**Comment by miningape** [comment]
I've added some steps to the readme. 

If you try running this just be aware the `/setup` page could be broken (I introduced some changes and never checked them lmao).
